export const PANORAMIC_IMAGE_URL = "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=2070&auto=format&fit=crop";

export const LOCALIZED_DATA = {
  CN: {
    nav: {
      caseMgmt: '病例管理',
      history: '历史记录',
      resources: '资源',
      support: '支持',
      newCase: '创建新病例',
      caseList: '病例列表'
    },
    labels: {
      systemTitle: '下颌第三磨牙-下牙槽神经手术风险评估系统',
      uploadTitle: '上传影像资料',
      uploadDesc: '选择全景片或 CBCT 影像以开始分析',
      dragDrop: '点击或拖拽全景片/CBCT',
      supportFormats: '支持 JPG, PNG, DICOM, NIFTI 格式',
      selectDevice: '从设备选择文件',
      startAnalysis: '开始分析',
      analysisHint: '点击“开始分析”将处理影像。完成后将在下方生成详细报告。',
      reportTitle: '分析报告',
      completed: '已完成',
      leftSide: '左侧',
      rightSide: '右侧',
      assessmentIndicators: '风险评估指标',
      toothPosition: '牙位',
      fdiCode: 'FDI 编码',
      minDistance: '最小距离',
      contactRelationship: '接触关系',
      relativePosition: '相对位置',
      riskScore: '风险评分',
      injuryProbability: '损伤概率',
      highRiskImagingSigns: '高危影像学征象',
      multiViewReconstruction: '多视角重建',
      clinicalRecommendation: '临床建议',
      riskWarning: '高风险警告',
      pdfReport: '生成完整 PDF 报告',
      mask: '分割',
      heatmap: 'Grad-CAM',
      grayscale: '灰度'
    },
    highRiskSigns: ['神经管变窄', '根尖弯曲', '根分叉暗影'],
  },
  EN: {
    nav: {
      caseMgmt: 'Case Management',
      history: 'History',
      resources: 'Resources',
      support: 'Support',
      newCase: 'Create New Case',
      caseList: 'Case List'
    },
    labels: {
      systemTitle: 'Mandibular Third Molar - IAC Surgery Risk Assessment System',
      uploadTitle: 'Upload Diagnostic Imaging',
      uploadDesc: 'Select files to begin a new M3-IAC analysis.',
      dragDrop: 'Drag and drop radiographs or CBCT',
      supportFormats: 'Support for JPG, PNG, DICOM, NIFTI',
      selectDevice: 'Select Files from Device',
      startAnalysis: 'Start Analysis',
      analysisHint: 'Clicking "Start Analysis" will process the images. The detailed report will be generated below upon completion.',
      reportTitle: 'Analysis Report',
      completed: 'COMPLETED',
      leftSide: 'Left Side',
      rightSide: 'Right Side',
      assessmentIndicators: 'Risk Assessment Indicators',
      toothPosition: 'Tooth Position',
      fdiCode: 'FDI Code',
      minDistance: 'Minimum Distance',
      contactRelationship: 'Contact Relationship',
      relativePosition: 'Relative Position',
      riskScore: 'Risk Score',
      injuryProbability: 'Injury Probability',
      highRiskImagingSigns: 'High-risk Imaging Signs',
      multiViewReconstruction: 'Multi-angle Reconstruction',
      clinicalRecommendation: 'Clinical Recommendations',
      riskWarning: 'HIGH RISK WARNING',
      pdfReport: 'Generate Full PDF Report',
      mask: 'SEGMENTATION',
      heatmap: 'Grad-CAM',
      grayscale: 'GRAYSCALE'
    },
    highRiskSigns: ['Canal Narrowing', 'Root Curvature', 'Bifurcation Radiolucency'],
  },
  JP: {
    nav: {
      caseMgmt: '症例管理',
      history: '履歴',
      resources: 'リソース',
      support: 'サポート',
      newCase: '新規症例作成',
      caseList: '症例一覧'
    },
    labels: {
      systemTitle: '下顎第三大臼歯-下歯槽神経手術リスク評価システム',
      uploadTitle: '診断画像のアップロード',
      uploadDesc: '新しいM3-IAC分析を開始するファイルを選択してください。',
      dragDrop: 'パノラマ画像またはCBCTをドラッグ＆ドロップ',
      supportFormats: 'JPG, PNG, DICOM, NIFTI 形式をサポート',
      selectDevice: 'デバイスからファイルを選択',
      startAnalysis: '分析開始',
      analysisHint: '「分析開始」をクリックすると画像が処理されます。完了後、下に詳細レポートが生成されます。',
      reportTitle: '分析レポート',
      completed: '完了',
      leftSide: '左側',
      rightSide: '右側',
      assessmentIndicators: 'リスク評価指標',
      toothPosition: '歯位',
      fdiCode: 'FDIコード',
      minDistance: '最小距離',
      contactRelationship: '接触関係',
      relativePosition: '相対位置',
      riskScore: 'リスクスコア',
      injuryProbability: '損傷確率',
      highRiskImagingSigns: '高リスク画像所見',
      multiViewReconstruction: '多角的な再構成',
      clinicalRecommendation: '臨床推奨事項',
      riskWarning: '高リスク警告',
      pdfReport: '全体PDFレポートを作成',
      mask: 'セグメンテーション',
      heatmap: 'Grad-CAM',
      grayscale: 'グレースケール'
    },
    highRiskSigns: ['管の狭窄', '歯根の湾曲', '分岐部の透過像'],
  }
};